version: '3.1'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: demo_yii2
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  db:
    image: mysql
    restart: always
    container_name: demo_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'